In [1]:
import scipy.sparse as sp
import numpy as np
indptr= np.array([0,2,3,6])
indices = np.array([0,2,2,0,1,2])
data = np.array([1,2,3,4,5,6])
csr = sp.csr_matrix((data,indices,indptr),shape=(3,3))

a = [0,1,2]
b = [2,0,1]
print(csr,'\n csr')
lil = csr.tolil()
print(lil,'\n lil')
print(lil.toarray())
print(lil[b,:],'\n b')
print(lil[a,:],'\n a')
lil[b,:]=lil[a,:]
print(lil,'\n lil[b,:]=lil[a,:]')

  (0, 0)	1
  (0, 2)	2
  (1, 2)	3
  (2, 0)	4
  (2, 1)	5
  (2, 2)	6 
 csr
  (0, 0)	1
  (0, 2)	2
  (1, 2)	3
  (2, 0)	4
  (2, 1)	5
  (2, 2)	6 
 lil
[[1 0 2]
 [0 0 3]
 [4 5 6]]
  (0, 0)	4
  (0, 1)	5
  (0, 2)	6
  (1, 0)	1
  (1, 2)	2
  (2, 2)	3 
 b
  (0, 0)	1
  (0, 2)	2
  (1, 2)	3
  (2, 0)	4
  (2, 1)	5
  (2, 2)	6 
 a
  (0, 2)	3
  (1, 0)	4
  (1, 1)	5
  (1, 2)	6
  (2, 0)	1
  (2, 2)	2 
 lil[b,:]=lil[a,:]


In [5]:
a=np.arange(12).reshape(2,6)
print(a)
print(np.argmax(a,1))
b=np.arange(24).reshape(2,3,4)
print(b)
print(np.argmax(b,1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[5 5]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[2 2 2 2]
 [2 2 2 2]]


In [18]:
import scipy.sparse as sp
import numpy as np
indptr= np.array([0,2,3,6])
indices = np.array([0,2,2,0,1,2])
data = np.array([1,2,3,4,5,6])
csr = sp.csr_matrix((data,indices,indptr),shape=(3,3)).toarray()
print(csr)
_csr = csr  + sp.eye(csr.shape[0])
print(_csr)
_dseq = _csr.sum(1).A1
print(type(_dseq), _dseq)
_tmp = np.power(_dseq, -0.5)
print(type(_tmp), _tmp.shape, _tmp)
_dig = sp.diags(_tmp)
print(type(_dig), _dig.toarray())

[[1 0 2]
 [0 0 3]
 [4 5 6]]
[[2. 0. 2.]
 [0. 1. 3.]
 [4. 5. 7.]]
<class 'numpy.ndarray'> [ 4.  4. 16.]
<class 'numpy.ndarray'> (3,) [0.5  0.5  0.25]
<class 'scipy.sparse.dia.dia_matrix'> [[0.5  0.   0.  ]
 [0.   0.5  0.  ]
 [0.   0.   0.25]]


In [16]:
    _adj = adj + sp.eye(adj.shape[0])
    # _dseq: 各个节点的度构成的列表
    _dseq = _adj.sum(1).A1
    # 构造开根号的度矩阵
    _D_half = sp.diags(np.power(_dseq, -0.5))
    # 计算标准化的邻接矩阵, @ 表示矩阵乘法
    adj_normalized = _D_half @ _adj @ _D_half
    return adj_normalized.tocsr()

NameError: name 'adj' is not defined