# Pytorch 基础

### Numpy

In [124]:
import numpy as np

arr_1_d = np.asarray([1])
print(arr_1_d)
arr_2_d = np.asarray([[1,2],[3,4],[5,6]])
print(arr_2_d)
print(arr_2_d.shape)
print( arr_2_d.ndim)
print('size:', arr_2_d.size)
print('dtype:', arr_2_d.dtype)
print('dtype:', arr_2_d.astype('float').dtype)

print(arr_2_d.reshape((2,3)))
print(arr_2_d.reshape((6,1)))
print(np.reshape(arr_2_d, (2,3)))
print(np.reshape(arr_2_d, (2,3), 'F'))
print(np.reshape(arr_2_d, (2,3), 'A'))

[1]
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2
size: 6
dtype: int64
dtype: float64
[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]]
[[1 5 4]
 [3 2 6]]
[[1 2 3]
 [4 5 6]]


In [33]:
print(np.ones(shape=(2,5)))
print(np.ones(shape=(2,5),dtype='int32'))
print(np.zeros(shape=(2,5)))
print(np.zeros(shape=(2,5),dtype='int32'))
print(np.ones(shape=(2,5),dtype='int32')*0.5)

print(np.arange(6))
print(np.arange(1,7))
print(np.arange(1,7,2))
interest_score = np.random.randint(10, size=(4, 3))
print(interest_score)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]]
[0 1 2 3 4 5]
[1 2 3 4 5 6]
[1 3 5]
[[3 8 7]
 [4 5 9]
 [8 0 7]
 [9 8 3]]


In [29]:
print(np.linspace(start=2, stop=10, num=3))

[ 2.  6. 10.]


In [30]:

import numpy as np
import matplotlib.pyplot as plt

X = np.arange(-50, 51, 2)
Y = X ** 2

plt.plot(X, Y, color='blue')
plt.legend()
plt.show()

No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.


In [35]:
interest_score = np.random.randint(10, size=(4, 3))
print(interest_score)
print(np.sum(interest_score, axis=0))
print(np.sum(interest_score, axis=1))

[[8 0 8]
 [2 2 9]
 [6 0 8]
 [9 6 7]]


[25  8 32]
[16 13 14 22]


In [41]:
a = np.arange(18).reshape(3,2,3)
print(a)
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))
print(np.sum(a, axis=2))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
[[18 21 24]
 [27 30 33]]
[[ 3  5  7]
 [15 17 19]
 [27 29 31]]
[[ 3 12]
 [21 30]
 [39 48]]


In [103]:
from PIL import Image
# Pillow 读入后通道的顺序就是 R、G、B
im = Image.open('../data/img/jike.png')
print(im.size, type(im))
im_pillow = np.asarray(im)
print( im_pillow.shape,im_pillow.dtype, im_pillow.ndim)


(510, 130) <class 'PIL.PngImagePlugin.PngImageFile'>
(130, 510, 4) uint8 3


In [104]:
import cv2
# OpenCV 读入后顺序是 B、G、R。
im_cv2 = cv2.imread('../data/img/jike.png')
print(type(im_cv2))
print(im_cv2.size, im_cv2.shape, im_cv2.dtype, im_cv2.ndim)


<class 'numpy.ndarray'>
198900 (130, 510, 3) uint8 3


In [105]:
print('im_pillow0', im_pillow[:,:,0])
print('im_pillow1', im_pillow[:,:,1])
print('im_pillow2', im_pillow[:,:,2])

print('im_cv2',im_cv2[:,:,2])

im_pillow0 [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
im_pillow1 [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
im_pillow2 [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
im_cv2 [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [106]:
zeros = np.zeros((im_cv2.shape[0],im_cv2.shape[1], 1))
print(zeros.shape)

(130, 510, 1)


In [107]:
im_cv2_c1 = im_cv2[:, :, 0]
im_cv2_c2 = im_cv2[:, :, 1]
im_cv2_c3 = im_cv2[:, :, 2]

#使用 np.newaxis 让数组增加一个维度
im_cv2_c1 = im_cv2_c1[:,:, np.newaxis]
print(im_pillow_c1_.shape)

(204, 174, 1)


In [108]:

im_cv2_c1_3ch = np.concatenate(( im_cv2_c1, zeros, zeros),axis=2)
print(im_cv2_c1_3ch.shape)


(130, 510, 3)


In [110]:
print( im_cv2.shape)
im_cv2_c2_3ch = np.zeros( im_cv2.shape)
im_cv2_c2_3ch[:,:,1] = im_cv2_c2
print( im_cv2_c2_3ch.shape)
im_cv2_c3_3ch = np.zeros( im_cv2.shape)
im_cv2_c3_3ch[:,:,2] =  im_cv2_c3
print( im_cv2_c3_3ch.shape)


(130, 510, 3)
(130, 510, 3)
(130, 510, 3)


In [112]:

from matplotlib import pyplot as plt
plt.subplot(2, 2, 1)
plt.title('Origin Image')
plt.imshow( im_cv2)
plt.axis('off')
plt.subplot(2, 2, 2)
plt.title('Red Channel')
plt.imshow( im_cv2_c1_3ch.astype(np.uint8))
plt.axis('off')
plt.subplot(2, 2, 3)
plt.title('Green Channel')
plt.imshow( im_cv2_c2_3ch.astype(np.uint8))
plt.axis('off')
plt.subplot(2, 2, 4)
plt.title('Blue Channel')
plt.imshow( im_cv2_c3_3ch.astype(np.uint8))
plt.axis('off')
plt.savefig('./rgb_pillow.png', dpi=150)

##### 深拷贝（副本）与浅拷贝（视图）

In [113]:
#  view() 浅拷贝, np.asarray()浅拷贝
a = np.arange(6)
print(a.shape)

print(a)

b = a.view()
print(b.shape)
b.shape = 2, 3
print(b)
b[0,0] = 111
print(a)
print(b)


(6,)
[0 1 2 3 4 5]
(6,)
[[0 1 2]
 [3 4 5]]
[111   1   2   3   4   5]
[[111   1   2]
 [  3   4   5]]


In [117]:
# np.arrray() 深拷贝

deep_a = np.array(a)
lite_a =np.asarray(a)
deep_a[1]=121
lite_a[1]=12
print(a)
print(deep_a)
print(lite_a)

[111  12   2   3   4   5]
[111 121   2   3   4   5]
[111  12   2   3   4   5]


In [120]:
probs = np.array([0.075, 0.15, 0.075, 0.15, 0.0, 0.05, 0.05, 0.2, 0.25])
print(np.argmax(probs))
print(np.argmin(probs))

8
4


In [122]:
probs_idx_sort1 = np.argsort(probs)  
print(probs_idx_sort1)
print(probs_idx_sort1[:3])
probs_idx_sort = np.argsort(-probs)  #注意，加了负号，是按降序排序
print(probs_idx_sort)
#概率最大的前三个值的坐标
print(probs_idx_sort[:3])


[4 5 6 0 2 1 3 7 8]
[4 5 6]
[8 7 1 3 0 2 5 6 4]
[8 7 1]


### Tensor in Pytorch

#### 创建Tensor

In [125]:
import torch
print(torch.tensor([1,2,3]))
print(torch.from_numpy(probs_idx_sort1))

tensor([1, 2, 3])
tensor([4, 5, 6, 0, 2, 1, 3, 7, 8])


In [135]:
print(torch.zeros(2, 3))
print(torch.eye(3))
print(torch.ones(2, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [141]:
print(torch.rand((2,3)))
print(torch.randn((2,3)))
print(torch.normal(0, 1, (3,2)))
print(torch.randint(1, 10, (2,3)))

tensor([[0.4107, 0.1699, 0.0625],
        [0.6527, 0.7045, 0.3808]])
tensor([[-0.9615,  0.5020, -0.7576],
        [ 0.7207,  0.7236,  0.1284]])
tensor([[-0.2771,  0.4383],
        [ 0.5597,  0.2501],
        [-0.7430, -0.6000]])
tensor([[8, 2, 9],
        [9, 4, 4]])


#### Tensor 常用操作

In [147]:
# 获取形状和元素数目
a = torch.zeros(2,3,4)
print(a.shape, type(a))
print(a.size())
print(a.numel()) # 总数

torch.Size([2, 3, 4]) <class 'torch.Tensor'>
torch.Size([2, 3, 4])
24


In [148]:
# 矩阵转换
x = torch.randn((2,3,4))
print(x.shape, x)
x = x.permute(2,1,0)
print(x.shape, x)
x = x.transpose(1,0)
print(x.shape, x)


torch.Size([2, 3, 4]) tensor([[[ 0.0362, -1.4494,  0.4976, -0.2643],
         [ 1.8913, -0.4740,  0.0393, -1.0073],
         [-0.6387, -0.1377, -0.2994,  0.8014]],

        [[-0.4006, -2.3914,  1.7749,  1.2583],
         [-0.0912, -1.0375, -0.7213,  0.3766],
         [ 0.5855,  0.7902,  0.1429,  0.3467]]])
torch.Size([4, 3, 2]) tensor([[[ 0.0362, -0.4006],
         [ 1.8913, -0.0912],
         [-0.6387,  0.5855]],

        [[-1.4494, -2.3914],
         [-0.4740, -1.0375],
         [-0.1377,  0.7902]],

        [[ 0.4976,  1.7749],
         [ 0.0393, -0.7213],
         [-0.2994,  0.1429]],

        [[-0.2643,  1.2583],
         [-1.0073,  0.3766],
         [ 0.8014,  0.3467]]])
torch.Size([3, 4, 2]) tensor([[[ 0.0362, -0.4006],
         [-1.4494, -2.3914],
         [ 0.4976,  1.7749],
         [-0.2643,  1.2583]],

        [[ 1.8913, -0.0912],
         [-0.4740, -1.0375],
         [ 0.0393, -0.7213],
         [-1.0073,  0.3766]],

        [[-0.6387,  0.5855],
         [-0.1377,  0.7902]

In [151]:
# 形状变换
x1 = torch.randn(4,4)
x1 = x1.view(2,8)
x1 = x1.permute(1,0)
x2 = x1.reshape(4,4)
print(x1,'\n', x2)

tensor([[ 0.2669,  0.3427],
        [ 0.1282,  2.3353],
        [-1.4883,  1.0169],
        [-0.0420, -0.0129],
        [ 0.9634,  0.8979],
        [ 1.6766, -1.6473],
        [ 1.6748,  0.6131],
        [ 0.3279, -0.7513]]) 
 tensor([[ 0.2669,  0.3427,  0.1282,  2.3353],
        [-1.4883,  1.0169, -0.0420, -0.0129],
        [ 0.9634,  0.8979,  1.6766, -1.6473],
        [ 1.6748,  0.6131,  0.3279, -0.7513]])


In [154]:
# 增减纬度
x2 = torch.randn(2,1,3)
print(x2.shape)
x2 = x2.squeeze(1)
print(x2.shape)
x2 = x2.unsqueeze(1)
print(x2.shape)

torch.Size([2, 1, 3])
torch.Size([2, 3])
torch.Size([2, 1, 3])


In [156]:
# 数据连接
##数据拼接
x3 = torch.ones((3,3))
x4 = 2*torch.ones((3,3))
print(torch.cat((x3,x4), 0))
print(torch.cat((x3,x4), 1))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.]])


In [158]:
##增加纬度连接
x5 = torch.arange(0,4)
x6 = torch.arange(5,9)
x7 = torch.stack((x5,x6), 0)
x8 = torch.stack((x5,x6), 1)
print(x5)
print(x6)
print(x7)
print(x8)

tensor([0, 1, 2, 3])
tensor([5, 6, 7, 8])
tensor([[0, 1, 2, 3],
        [5, 6, 7, 8]])
tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8]])


In [161]:
# 切分
x8 = torch.arange(1,11)
print(x8)
x9 = torch.chunk(x8, 3, 0)
print(x9)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
(tensor([1, 2, 3, 4]), tensor([5, 6, 7, 8]), tensor([ 9, 10]))


In [167]:
A = torch.randn((5,4))
B = torch.split(A, (3,2), 0)
print(A)
print(B)
print(type(B))

tensor([[ 0.5771,  0.4759,  0.6465, -0.6423],
        [ 1.2316,  0.5598, -1.9431,  0.8217],
        [ 0.2705,  0.6665, -1.9078, -2.2760],
        [ 0.9028,  0.9447, -1.8418,  0.9417],
        [-1.6166,  0.3329,  0.3391,  1.5699]])
(tensor([[ 0.5771,  0.4759,  0.6465, -0.6423],
        [ 1.2316,  0.5598, -1.9431,  0.8217],
        [ 0.2705,  0.6665, -1.9078, -2.2760]]), tensor([[ 0.9028,  0.9447, -1.8418,  0.9417],
        [-1.6166,  0.3329,  0.3391,  1.5699]]))
<class 'tuple'>


In [168]:
A = torch.randn((4,4))
print(A)
B = torch.unbind(A, 0)
print(B)
C = torch.unbind(A, 1 )
print(C)

tensor([[-0.5326, -0.0536,  1.3403, -0.4589],
        [-0.2208,  0.0348, -0.8601, -0.9665],
        [-1.2152, -0.9435, -1.4405, -0.1171],
        [-0.0767, -0.1384,  0.7953,  1.4175]])
(tensor([-0.5326, -0.0536,  1.3403, -0.4589]), tensor([-0.2208,  0.0348, -0.8601, -0.9665]), tensor([-1.2152, -0.9435, -1.4405, -0.1171]), tensor([-0.0767, -0.1384,  0.7953,  1.4175]))
(tensor([-0.5326, -0.2208, -1.2152, -0.0767]), tensor([-0.0536,  0.0348, -0.9435, -0.1384]), tensor([ 1.3403, -0.8601, -1.4405,  0.7953]), tensor([-0.4589, -0.9665, -0.1171,  1.4175]))


In [170]:
# 索引操作
A = torch.arange(16).view(4,4)
print(A)
B = torch.index_select(A, 0, torch.tensor([1,3]))
print(B)
C = torch.index_select(A, 1, torch.tensor([1,3]))
print(C)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[ 4,  5,  6,  7],
        [12, 13, 14, 15]])
tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15]])


In [174]:
A = torch.randn((4))
B = A > 0.5
C = torch.masked_select(A, B)
print(A)
print(B)
print(C)
print(torch.masked_select(A, A>0))


tensor([-0.1057,  0.0884,  0.5022, -0.5478])
tensor([False, False,  True, False])
tensor([0.5022])
tensor([0.0884, 0.5022])
