# Tensorflow 中的乘法

#### tf.multiply(A, B) = `A * B` : 矩阵元素乘法(element-wise) 
`tf.multiply`和`*`一样，是两个tensor的元素相乘（element-wise操作)。要求如下： 
1. 两个tensor的数据类型相同， 
2. 两个tensor的维度相同。或经过扩纬和广播(只支持size为1的维度广播)操作后相同。
包括3种情况：
+ 


In [20]:
import tensorflow as tf
import numpy as np

def test_multiply():
    A = 2
    B = 3
    C = 4
    size = A * B * C
    x0 = tf.Variable(np.random.randint(1, 9, size=A*B*C, dtype='int32').reshape([A, B,C]), name = 'x0', dtype=tf.int32)
    x1 = tf.Variable(np.random.randint(1, 9, size=A*B*C, dtype='int32').reshape([A, B,C]), name = 'x1',dtype=tf.int32)
    x2 = tf.Variable(np.random.randint(1, 9, size=1*B*C, dtype='int32').reshape([1, B,C]), name = 'x2', dtype=tf.int32)
    x3 = tf.Variable(np.random.randint(1, 9, size=A*1*C, dtype='int32').reshape([A, 1,C]), name = 'x3',dtype=tf.int32)
    x4 = tf.Variable(np.random.randint(1, 9, size=1*1*C, dtype='int32').reshape([1, 1,C]), name = 'x4',dtype=tf.int32)
    x5 = tf.Variable(np.random.randint(1, 9, size=1*1*1, dtype='int32').reshape([1, 1,1]), name = 'x5',dtype=tf.int32)
    x6 = tf.Variable(np.random.randint(1, 9, size=B*C, dtype='int32').reshape([B,C]), name = 'x6',dtype=tf.int32)
    x7 = tf.Variable(np.random.randint(1, 9, size=C, dtype='int32').reshape([C]), name = 'x7',dtype=tf.int32)
    x8 = tf.Variable(np.random.randint(1, 9, size=1, dtype='int32').reshape([1]), name = 'x8',dtype=tf.int32)
    y1 = tf.multiply(x0, x1, name = 'y1')
    y2 = tf.multiply(x0, x2, name = 'y2')
    y3 = tf.multiply(x0, x3, name = 'y3')
    y4 = tf.multiply(x0, x4, name = 'y4')
    y5 = tf.multiply(x0, x5, name = 'y5')
    y6 = tf.multiply(x0, x6, name = 'y6')
    y7 = tf.multiply(x0, x7, name = 'y7')
    y8 = tf.multiply(x0, x8, name = 'y8')
    print(x0.name,x0.shape)
    print(x1.name,x1.shape)
    print(x2.name,x2.shape)
    print(x3.name,x3.shape)
    print(x4.name,x4.shape)
    print(x5.name,x5.shape)
    print(x6.name,x6.shape)
    print(x7.name,x7.shape)
    print(x8.name,x8.shape)
    
    #print(x0)
    #print(x1)
    #print(x2)
    #print(x3)
    #print(x4)
    #print(x5)
    #print(x6)
    #print(x7)
    #print(x8)
    #print('y1: ',y1)
    #print('y2: ',y2)
    #print('y3: ',y3)
    #print('y4: ',y4)
    #print('y5: ',y5)
    #print('y6: ',y6)
    #print('y7: ',y7)
    #print('y8: ',y8)
    
test_multiply()

x0:0 (2, 3, 4)
x1:0 (2, 3, 4)
x2:0 (1, 3, 4)
x3:0 (2, 1, 4)
x4:0 (1, 1, 4)
x5:0 (1, 1, 1)
x6:0 (3, 4)
x7:0 (4,)
x8:0 (1,)


#### tf.matmul(A, B)
`tf.matmul` 是矩阵乘法。 A,B 的最后两维进行进行矩阵乘法运算。 要求是：1， 矩阵A，B的数据类型相同。2，矩阵A，B的最后两维满足满足矩阵乘法的要求。其余维度不相同时，会先进行扩纬然后对应维度广播使两者shape相同。


#### tf.tensordot( a, b,axes,name=None)
`tf.tensordot` 也称为张量收缩。是指定特定轴的矩阵相乘。通过参数axes指定轴，两个tensor沿着指定轴进行张量收缩。收缩方式是矩阵乘法求和，或者理解为矩阵平铺成一维向量内积求和。
这里参数axes有两种形式：
+ axes参数是一个数值n，表示a的后n维形成的矩阵和b的前n维形成的矩阵，平铺成一维向量后做内积。弱axes=0,则表示两个tensor进行外积。
+ axes的参数是两个list, 表示a在指定维度形成的矩阵和b在指定维度形成的矩阵，分平铺成一维向量后做内积；内积值则为结果tensor对应位置的值。
下面是一些
| tensor X1 shape | tensor X2 shape | axes             | 要求                                                  | 结果shape |
| --------------- | --------------- | ---------------- | ------------------------------------------------------- | --------- |
| [2,4,6]         | [9,4,6]         | ([2],[2])        | X1第2维值=X2第2维值                               | [2,4,9,4] |
| [2,4,6]         | [9,4,6]         | ([1,2],[1,2])    | X1第1维和第2维的值连乘=X2的第1维和第2维值连乘(4*6=4*6) | [2, 9]    |
| [2,4,6]         | [4,6,9]         | ([1,2],[0,1])    | X1第1维和第2维的值连乘=X2的第0维和第1维值连乘(4*6=4*6) | [2,9]     |
| [2,4,6]         | [4,3,6,9]       | ([1,2],[0,2])    | X1第1维和第2维的值连乘=X2的第0维和第2维值连乘(4*6=4*6) | [2,3,9]   |
| [2,4,6]         | [4,6]           | 2或([1,2],[0,1]) | X1第1维和第2维的值连乘=X2的第0维和第1维值连乘(4*6=4*6) | [2]       |
| [2,4,6]         | [9,2,12]        | ([1,2],[1,2])    | X1第1维和第2维的值连乘=X2的第1维和第2维值连乘(4*6=1*12) | [2,9]     |


In [40]:
import tensorflow as tf
import numpy as np

def test_tensordot():
    x0 = tf.Variable(np.random.randint(1, 9, size=2*4*6, dtype='int32').reshape([2, 4, 6]), name = 'x0', dtype=tf.int32)
    x1 = tf.Variable(np.random.randint(1, 9, size=9*4*6, dtype='int32').reshape([9, 4, 6]), name = 'x1',dtype=tf.int32)
    x2 = tf.Variable(np.random.randint(1, 9, size=4*6*9, dtype='int32').reshape([4, 6,9]), name = 'x2', dtype=tf.int32)
    x3 = tf.Variable(np.random.randint(1, 9, size=4*3*6*9, dtype='int32').reshape([4,3,6,9]), name = 'x3',dtype=tf.int32)
    x4 = tf.Variable(np.random.randint(1, 9, size=4*6, dtype='int32').reshape([4,6]), name = 'x4',dtype=tf.int32)
    x5 = tf.Variable(np.random.randint(1, 9, size=9*2*12, dtype='int32').reshape([9, 2,12]), name = 'x5',dtype=tf.int32)
    y11 = tf.tensordot(x0, x1, axes=([2], [2]))
    y12 = tf.tensordot(x0, x1, axes=([1,2], [1,2]))
    y2 = tf.tensordot(x0, x2, axes=([1, 2], [0, 1]))
    y3 = tf.tensordot(x0, x3, axes=([1, 2], [0, 2]))
    y4= tf.tensordot(x0, x4, axes=([1, 2], [0, 1]))
    y5 = tf.tensordot(x0, x5, axes=([1, 2], [1, 2]))
    
    

  
    
    #print(x0.name,x0.shape)
    #print(x1.name,x1.shape)
    #print(x2.name,x2.shape)
    #print(x3.name,x3.shape)
    #print(x4.name,x4.shape)
    #print(x5.name,x5.shape)
    #print('y11: ',y11.shape)
    #print('y12: ',y12.shape)
    #print('y2: ',y2.shape)
    #print('y3: ',y3.shape)
    #print('y4: ',y4.shape)
    #print('y5: ',y5.shape)

    #print(x0)
    #print(x1)
    #print(x2)
    #print(x3)
    #print(x4)
    #print(x5)
    #print('y11: ',y11)
    #print('y12: ',y12)

    #print('y2: ',y2)
    #print('y3: ',y3)
    #print('y4: ',y4)
    #print('y5: ',y5)
    #print('y6: ',y6)
    #print('y7: ',y7)
    #print('y8: ',y8)
    
    x6 = tf.Variable(np.random.randint(1, 9, size=2*3*2, dtype='int32').reshape([2, 3,2]), name = 'x0', dtype=tf.int32)
    x7 = tf.Variable(np.random.randint(1, 9, size=2*3*4*5, dtype='int32').reshape([2, 3,4,5]), name = 'x1',dtype=tf.int32)

    y67 = tf.tensordot(x6, x7, axes=([1],[1]))

    print(x6)
    print(x7)
    print(y67)

    
test_tensordot()

<tf.Variable 'x0:0' shape=(2, 3, 2) dtype=int32, numpy=
array([[[7, 7],
        [6, 8],
        [5, 4]],

       [[1, 2],
        [1, 2],
        [8, 6]]], dtype=int32)>
<tf.Variable 'x1:0' shape=(2, 3, 4, 5) dtype=int32, numpy=
array([[[[5, 3, 4, 1, 3],
         [3, 2, 1, 3, 7],
         [7, 7, 5, 3, 7],
         [3, 6, 8, 8, 5]],

        [[5, 5, 4, 3, 7],
         [7, 1, 7, 7, 2],
         [8, 4, 5, 6, 6],
         [3, 4, 3, 4, 1]],

        [[6, 8, 1, 2, 4],
         [1, 8, 5, 6, 7],
         [4, 7, 1, 2, 5],
         [8, 4, 7, 4, 4]]],


       [[[5, 6, 8, 2, 5],
         [3, 3, 7, 3, 7],
         [4, 1, 6, 4, 2],
         [7, 8, 4, 4, 3]],

        [[7, 5, 5, 7, 4],
         [1, 2, 6, 3, 8],
         [3, 5, 4, 4, 7],
         [1, 8, 5, 7, 8]],

        [[1, 6, 5, 8, 7],
         [1, 1, 7, 5, 7],
         [7, 1, 5, 2, 6],
         [5, 8, 7, 2, 1]]]], dtype=int32)>
tf.Tensor(
[[[[[ 95  91  57  35  83]
    [ 68  60  74  93  96]
    [117 108  70  67 110]
    [ 79  86 109 100  61]]

 

## 