# Tensorflow 2.6 API

In [3]:
import tensorflow as tf

#### tf.expand_dims(input, axis, name=None)
增加维度：在索引axis 轴，添加 1 个尺寸的维度。

In [ ]:
import  tensorflow as tf
image = tf.zeros([10,10,3])
print(tf.expand_dims(image, axis=0).shape.as_list())
print(tf.expand_dims(image, axis=1).shape.as_list())
print(tf.expand_dims(image, axis=-1).shape.as_list())

##### tf.sequence_mask(lengths, maxlen=None, dtype=tf.dtypes.bool, name=None)
用于数据填充

In [8]:
import tensorflow as tf
print(tf.sequence_mask([1, 3, 2], 5))
print(tf.sequence_mask([[1, 3],[2,0]]))

tf.Tensor(
[[ True False False False False]
 [ True  True  True False False]
 [ True  True False False False]], shape=(3, 5), dtype=bool)
tf.Tensor(
[[[ True False False]
  [ True  True  True]]

 [[ True  True False]
  [False False False]]], shape=(2, 2, 3), dtype=bool)


#### tf.transpose(a, perm=None, conjugate=False, name='transpose')
矩阵转置

In [10]:
import tensorflow as tf

x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])
x_trans =tf.transpose(x, perm=[0, 2, 1])
print(x)
print(x_trans)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]], shape=(2, 3, 2), dtype=int32)


#### tf.tile(input, multiples, name=None)
张量平铺。创建一个用 multiples 平铺 的 input 张量。

#### tf.stack(values, axis=0, name='stack')
向量堆叠。将秩 为 R 的张量列表堆叠成秩为 R + 1 的张量。

In [16]:
x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])
print(x)
print(tf.stack([x, y, z]))
print(tf.stack([x, y, z], axis=1))
x = tf.constant([[1, 4],[3,2]])
y = tf.constant([[2, 5],[4,1]])
z = tf.constant([[3, 6],[3,4]])
print(x)
print(tf.stack([x, y, z]))
print(tf.stack([x, y, z], axis=1))
print(tf.stack([x, y, z], axis=2))

tf.Tensor([1 4], shape=(2,), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 4]
 [3 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[1 4]
  [3 2]]

 [[2 5]
  [4 1]]

 [[3 6]
  [3 4]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor(
[[[1 4]
  [2 5]
  [3 6]]

 [[3 2]
  [4 1]
  [3 4]]], shape=(2, 3, 2), dtype=int32)
tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[3 4 3]
  [2 1 4]]], shape=(2, 2, 3), dtype=int32)
